### PR TITLE
Class Work Practise of Class2

### PR DESCRIPTION
**Pull request by azm-mehedi-hasan**
Vaiya, please check the codes i practiced. I am still practicing now.

### CODE REVIEW

**Comment by tajnur007** [comment]
Delete "package-lock.json" file, "package.json" file and "node_modules" folder. We don't need to keep those files and folder.

**Comment by azm-mehedi-hasan** [comment]
Ok, Vaii. I took input from keyboard,  that's why i had to install promt
and those json files.
I will delete it as quick as possible

**Comment by tajnur007** [comment]
You can delete those files & folder and then do a commit & push it. Your PR will be updated.

**Comment by tajnur007** [comment]
One more thing, no need to mark as comment the codes into "classWork.js" file, just keep those comments as comment which are really comment.

**Comment by azm-mehedi-hasan** [comment]
Ok vai. Thanks

**Pull request merged**
